#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "pigeonpod"
name = "PigeonPod"
description.en = "Self-hosted RSS feeds from YouTube and Bilibili"
description.fr = "Flux RSS auto-hébergés depuis YouTube et Bilibili"
version = "1.30.0~ynh2"
maintainers = ["pigeonpod_ynh contributors"]

[upstream]
license = "GPL-3.0-only"
website = "https://pigeonpod.cloud/"
admindoc = "https://github.com/aizhimou/pigeon-pod/wiki/Installation"
userdoc = "https://github.com/aizhimou/pigeon-pod/wiki/Daily-Usage"
code = "https://github.com/aizhimou/pigeon-pod"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "1G"
ram.build = "2G"
ram.runtime = "1G"

[install]

[install.domain]
type = "domain"

[install.init_main_permission]
type = "group"
default = "visitors"

[resources]

[resources.sources]
[resources.sources.main]
url = "https://github.com/aizhimou/pigeon-pod/archive/refs/tags/1.30.0.tar.gz"
sha256 = "66b25d748893a1ac01bc59a6b14f7167810c3eead4102c00b4c2b1a80e72b1e8"
in_subdir = true
autoupdate.strategy = "latest_github_tag"

[resources.sources.ytdlp]
url = "https://github.com/yt-dlp/yt-dlp/releases/download/2026.8.19/yt-dlp"
sha256 = "1fa6733c37ea6fb51c99ad8fe785e7b7e5f3246c9b980230329d4fb72ed8d4d6"
extract = false
rename = "yt-dlp"
autoupdate.strategy = "latest_github_release"
autoupdate.asset = "^yt-dlp$"

[resources.system_user]

[resources.install_dir]

[resources.data_dir]
subdirs = ["audio", "video", "cover", "ssl", "tools"]

[resources.permissions]
main.url = "/"

[resources.ports]
main.default = 8834

[resources.apt]
packages = [
  "default-jdk-headless",
  "maven",
  "ffmpeg",
  "sqlite3"
]

[resources.nodejs]
version = "22"
