#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Stopping and removing PigeonPod service..."
ynh_systemctl --service="$app" --action="stop"

if ynh_hide_warnings yunohost service status "$app" >/dev/null 2>&1; then
  yunohost service remove "$app"
fi

ynh_config_remove_systemd
ynh_config_remove_nginx

ynh_safe_rm "/var/log/$app"

ynh_script_progression "Removal of PigeonPod completed"
